/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sanqing.struts.action;

import com.sanqing.struts.form.ActionEditorForm;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;

/**
 * MyEclipse Struts
 * Creation date: 04-18-2008
 * <p>
 * XDoclet definition:
 *
 * @struts.action path="/actionEditor" name="actionEditorForm" input="/form/employee/actionEditor.jsp" scope="request" validate="true"
 */
public class ActionEditorAction extends Action {
    /*
	 * Generated Methods
	 */

    /**
     * Method execute
     *
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward execute(ActionMapping mapping, ActionForm form,
                                 HttpServletRequest request, HttpServletResponse response) {
        ActionEditorForm actionEditorForm = (ActionEditorForm) form;// TODO Auto-generated method stub
        try {
            PrintWriter out = response.getWriter();
            try {
                String oper = request.getParameter("oper");
                com.sanqing.bll.BAction B_V = new com.sanqing.bll.BAction();
                if (oper.equals("add")) {
                    B_V.ActionmasterAdd(actionEditorForm);
                } else if (oper.equals("edit")) {
                    B_V.ActionmasterEdit(actionEditorForm);
                } else if (oper.equals("delete")) {
                    B_V.ActionmasterDelete(actionEditorForm.getAction_id());
                } else if (oper.equals("group")) {
                    out.print(B_V.ActionmasterGetAllGroup());
                    return null;
                }
                out.print(B_V.ActionmasterConvertToHTMLTable(request.getParameter("group")));

            } catch (Exception e) {
                out.print(e.getMessage());
            }

        } catch (IOException e1) {
            e1.printStackTrace();
        }
        return null;
    }
}