/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sanqing.struts.action;

import com.sanqing.struts.form.IussefailForm;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * MyEclipse Struts
 * Creation date: 04-20-2008
 * <p>
 * XDoclet definition:
 *
 * @struts.action path="/iussefail" name="iussefailForm" input="/form/storage/iussefail.jsp" scope="request" validate="true"
 */
public class IussefailAction extends Action {
    /*
	 * Generated Methods
	 */

    /**
     * Method execute
     *
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward execute(ActionMapping mapping, ActionForm form,
                                 HttpServletRequest request, HttpServletResponse response) {
        IussefailForm iussefailForm = (IussefailForm) form;// TODO Auto-generated method stub
        return null;
    }
}