/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sanqing.struts.action;

import com.sanqing.struts.form.RoleActionForm;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;

/**
 * MyEclipse Struts
 * Creation date: 04-29-2008
 * <p>
 * XDoclet definition:
 *
 * @struts.action path="/roleAction" name="roleActionForm" input="/form/systemManage/roleAction.jsp" scope="request" validate="true"
 */
public class RoleActionAction extends Action {
    /*
	 * Generated Methods
	 */

    /**
     * Method execute
     *
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward execute(ActionMapping mapping, ActionForm form,
                                 HttpServletRequest request, HttpServletResponse response) {
        RoleActionForm roleActionForm = (RoleActionForm) form;// TODO Auto-generated method stub
        try {
            PrintWriter out = response.getWriter();
            try {
                String oper = request.getParameter("oper");
                com.sanqing.bll.BAction B_V = new com.sanqing.bll.BAction();
                com.sanqing.bll.BRoleMaster B_R = new com.sanqing.bll.BRoleMaster();
                com.sanqing.bll.BRoleAction B_RA = new com.sanqing.bll.BRoleAction();
                if (oper.equals("comfirm")) {
                    B_RA.EditRoleActions(request);
                } else if (oper.equals("cancel")) {
                    //B_V.ActionmasterEdit(roleActionForm);
                } else if (oper.equals("getListByGroup")) {
                    //B_V.ActionmasterEdit(roleActionForm);
                } else if (oper.equals("getListByRole")) {
                    //B_V.ActionmasterEdit(roleActionForm);
                } else if (oper.equals("role")) {
                    out.print(B_R.RoleMasterConvertToHTMLTableName());
                    return null;
                } else if (oper.equals("group")) {
                    out.print(B_V.ActionmasterGetAllGroup());
                    return null;
                }
                out.print(B_RA.ActionmasterConvertToHTMLTableWithCheckBox(request.getParameter("group"), request.getParameter("role")));
            } catch (Exception e) {
                out.print(e.getMessage());
            }

        } catch (IOException e1) {
            e1.printStackTrace();
        }
        return null;
    }
}