/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sanqing.struts.action;

import com.sanqing.struts.form.UmmasterForm;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;

/**
 * MyEclipse Struts
 * Creation date: 04-18-2008
 * <p>
 * XDoclet definition:
 *
 * @struts.action path="/ummaster" name="ummasterForm" input="/form/systemManage/ummaster.jsp" scope="request" validate="true"
 */
public class UmmasterAction extends Action {
    /*
	 * Generated Methods
	 */

    /**
     * Method execute
     *
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward execute(ActionMapping mapping, ActionForm form,
                                 HttpServletRequest request, HttpServletResponse response) {
        UmmasterForm ummasterForm = (UmmasterForm) form;// TODO Auto-generated method stub
        try {
            PrintWriter out = response.getWriter();
            try {
                String oper = request.getParameter("oper");
                com.sanqing.bll.BUmMaster B_V = new com.sanqing.bll.BUmMaster();
                if (oper.equals("add")) {
                    B_V.UmMasterAdd(ummasterForm);
                } else if (oper.equals("edit")) {
                    B_V.UmMasterEdit(ummasterForm);
                } else if (oper.equals("delete")) {
                    B_V.UmMasterDelete(ummasterForm.getUm_id());
                }
                out.print(B_V.UmMasterConvertToHTMLTable());

            } catch (Exception e) {
                out.print(e.getMessage());
            }

        } catch (IOException e1) {
            e1.printStackTrace();
        }
        return null;
    }
}