/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sanqing.struts.action;

import com.sanqing.struts.form.UserEditorForm;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;

/**
 * MyEclipse Struts
 * Creation date: 04-18-2008
 * <p>
 * XDoclet definition:
 *
 * @struts.action path="/userEditor" name="userEditorForm" input="/form/employee/userEditor.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/form/employee/employeelist.jsp"
 */
public class UserEditorAction extends Action {
    /*
	 * Generated Methods
	 */

    /**
     * Method execute
     *
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward execute(ActionMapping mapping, ActionForm form,
                                 HttpServletRequest request, HttpServletResponse response) {
        UserEditorForm userEditorForm = (UserEditorForm) form;// TODO Auto-generated method stub
        try {
            PrintWriter out = response.getWriter();
            try {
                String oper = request.getParameter("oper");
                com.sanqing.bll.BEmployee B_V = new com.sanqing.bll.BEmployee();
                if (oper.equals("add")) {
                    B_V.ActionmasterAdd(userEditorForm);
                } else if (oper.equals("edit")) {
                    B_V.ActionmasterEdit(userEditorForm);
                } else if (oper.equals("delete")) {
                    B_V.ActionmasterDelete(userEditorForm.getEmp_id());
                } else if (oper.equals("model")) {
                    String Para = request.getParameter("employID");
                    String Temp = B_V.EmployeeConvertToJSON(Para);
                    out.print(Temp);
                    return null;
                } else if (oper.equals("passwordSet")) {
                    //B_V.UmMasterDelete(userEditorForm.getUm_id());
                    return null;
                } else if (oper.equals("roleSet")) {
                    //B_V.UmMasterDelete(userEditorForm.getUm_id());
                    return null;
                } else if (oper.equals("roleGet")) {
                    //B_V.UmMasterDelete(userEditorForm.getUm_id());
                    return null;
                }
                out.print(B_V.EmployeeConvertToHTMLTable());

            } catch (Exception e) {
                out.print(e.getMessage());
            }

        } catch (IOException e1) {
            e1.printStackTrace();
        }
        return null;
    }
}