/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sanqing.struts.action;

import com.sanqing.struts.form.VenderEditorForm;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;

/**
 * MyEclipse Struts
 * Creation date: 04-19-2008
 * <p>
 * XDoclet definition:
 *
 * @struts.action path="/venderEditor" name="venderEditorForm" input="/form/vender/venderEditor.jsp" scope="request" validate="true"
 */
public class VenderEditorAction extends Action {

	/*
	 * Generated Methods
	 */

    /**
     * Method execute
     *
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward execute(ActionMapping mapping, ActionForm form,
                                 HttpServletRequest request, HttpServletResponse response) {
        VenderEditorForm venderEditorForm = (VenderEditorForm) form;// TODO Auto-generated method stub
        try {
            PrintWriter out = response.getWriter();
            try {
                String oper = request.getParameter("oper");
                com.sanqing.bll.B_vender B_V = new com.sanqing.bll.B_vender();
                if (oper.equals("add")) {
                    HibernateDao.Vendermaster TypeModel = new HibernateDao.Vendermaster();
                    TypeModel.setContMan(venderEditorForm.getCont_man());
                    TypeModel.setShipvin(new HibernateDao.ShipvinDAO().findById(venderEditorForm.getVend_shipvia()));
                    TypeModel.setTradeAmount(Long.parseLong(venderEditorForm.getTradeamount()));
                    TypeModel.setVendAddr(venderEditorForm.getVend_addr());
                    TypeModel.setVendCity(venderEditorForm.getVend_city());
                    TypeModel.setVendDesc(venderEditorForm.getVend_desc());
                    TypeModel.setVendEmail(venderEditorForm.getVend_email());
                    TypeModel.setVendId(venderEditorForm.getVend_id());
                    TypeModel.setVendNati(venderEditorForm.getVend_nati());
                    TypeModel.setVendPhone(venderEditorForm.getVend_phone());
                    TypeModel.setVendPost(venderEditorForm.getVend_post());
                    TypeModel.setVendtype(new HibernateDao.VendtypeDAO().findById(venderEditorForm.getVend_type()));
                    B_V.M_Vend_Add(TypeModel);
                } else if (oper.equals("edit")) {
                    HibernateDao.Vendermaster TypeModel = new HibernateDao.Vendermaster();
                    TypeModel.setContMan(venderEditorForm.getCont_man());
                    TypeModel.setShipvin(new HibernateDao.ShipvinDAO().findById(venderEditorForm.getVend_shipvia()));
                    String TempAmount = venderEditorForm.getTradeamount();
                    TypeModel.setTradeAmount(Long.parseLong(venderEditorForm.getTradeamount()));
                    TypeModel.setVendAddr(venderEditorForm.getVend_addr());
                    TypeModel.setVendCity(venderEditorForm.getVend_city());
                    TypeModel.setVendDesc(venderEditorForm.getVend_desc());
                    TypeModel.setVendEmail(venderEditorForm.getVend_email());
                    TypeModel.setVendId(venderEditorForm.getVend_id());
                    TypeModel.setVendNati(venderEditorForm.getVend_nati());
                    TypeModel.setVendPhone(venderEditorForm.getVend_phone());
                    TypeModel.setVendPost(venderEditorForm.getVend_post());
                    TypeModel.setVendtype(new HibernateDao.VendtypeDAO().findById(venderEditorForm.getVend_type()));
                    B_V.M_Vend_Edit(TypeModel);
                } else if (oper.equals("delete")) {
                    B_V.M_Vend_Delete(venderEditorForm.getVend_id());
                } else if (oper.equals("model")) {
                    out.print(B_V.M_Vend_ConvertModelToJson(request.getParameter("vend_id")));
                    return null;
                }
                out.print(B_V.M_Vend_ConvertToHTMLTable());

            } catch (Exception e) {
                out.print(e.getMessage());
            }

        } catch (IOException e1) {
            e1.printStackTrace();
        }
        return null;
    }
}