/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Tue Aug 28 18:29:26 CST 2007 by MyEclipse Hibernate Tool.
 */
package com.demo.hibernate.beans;

import java.io.Serializable;

/**
 * A class that represents a row in the meeting table.
 * You can customize the behavior of this class by editing the class, {@link Meeting()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractMeeting
        implements Serializable {
    /**
     * The cached hash code value for this instance.  Settting to 0 triggers re-calculation.
     */
    private int hashValue = 0;

    /**
     * The composite primary key value.
     */
    private Integer id;

    /**
     * The value of the simple sender property.
     */
    private String sender;

    /**
     * The value of the simple starttime property.
     */
    private String starttime;

    /**
     * The value of the simple endtime property.
     */
    private String endtime;

    /**
     * The value of the simple address property.
     */
    private String address;

    /**
     * The value of the simple title property.
     */
    private String title;

    /**
     * The value of the simple content property.
     */
    private String content;

    /**
     * Simple constructor of AbstractMeeting instances.
     */
    public AbstractMeeting() {
    }

    /**
     * Constructor of AbstractMeeting instances given a simple primary key.
     *
     * @param id
     */
    public AbstractMeeting(Integer id) {
        this.setId(id);
    }

    /**
     * Return the simple primary key value that identifies this object.
     *
     * @return java.lang.Integer
     */
    public Integer getId() {
        return id;
    }

    /**
     * Set the simple primary key value that identifies this object.
     *
     * @param id
     */
    public void setId(Integer id) {
        this.hashValue = 0;
        this.id = id;
    }

    /**
     * Return the value of the sender column.
     *
     * @return java.lang.String
     */
    public String getSender() {
        return this.sender;
    }

    /**
     * Set the value of the sender column.
     *
     * @param sender
     */
    public void setSender(String sender) {
        this.sender = sender;
    }

    /**
     * Return the value of the starttime column.
     *
     * @return java.lang.String
     */
    public String getStarttime() {
        return this.starttime;
    }

    /**
     * Set the value of the starttime column.
     *
     * @param starttime
     */
    public void setStarttime(String starttime) {
        this.starttime = starttime;
    }

    /**
     * Return the value of the endtime column.
     *
     * @return java.lang.String
     */
    public String getEndtime() {
        return this.endtime;
    }

    /**
     * Set the value of the endtime column.
     *
     * @param endtime
     */
    public void setEndtime(String endtime) {
        this.endtime = endtime;
    }

    /**
     * Return the value of the address column.
     *
     * @return java.lang.String
     */
    public String getAddress() {
        return this.address;
    }

    /**
     * Set the value of the address column.
     *
     * @param address
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * Return the value of the title column.
     *
     * @return java.lang.String
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Set the value of the title column.
     *
     * @param title
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Return the value of the content column.
     *
     * @return java.lang.String
     */
    public String getContent() {
        return this.content;
    }

    /**
     * Set the value of the content column.
     *
     * @param content
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     *
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs) {
        if (rhs == null)
            return false;
        if (!(rhs instanceof Meeting))
            return false;
        Meeting that = (Meeting) rhs;
        if (this.getId() == null || that.getId() == null)
            return false;
        return (this.getId().equals(that.getId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     *
     * @return int
     */
    public int hashCode() {
        if (this.hashValue == 0) {
            int result = 17;
            int idValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + idValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
