package HibernateDao;

import java.util.HashSet;
import java.util.Set;

/**
 * Classcode generated by MyEclipse Persistence Tools
 */

public class Classcode implements java.io.Serializable {

    // Fields

    private String prodId;

    private String prodDesc;

    private Set itemgenerals = new HashSet(0);

    // Constructors

    /**
     * default constructor
     */
    public Classcode() {
    }

    /**
     * minimal constructor
     */
    public Classcode(String prodId) {
        this.prodId = prodId;
    }

    /**
     * full constructor
     */
    public Classcode(String prodId, String prodDesc, Set itemgenerals) {
        this.prodId = prodId;
        this.prodDesc = prodDesc;
        this.itemgenerals = itemgenerals;
    }

    // Property accessors

    public String getProdId() {
        return this.prodId;
    }

    public void setProdId(String prodId) {
        this.prodId = prodId;
    }

    public String getProdDesc() {
        return this.prodDesc;
    }

    public void setProdDesc(String prodDesc) {
        this.prodDesc = prodDesc;
    }

    public Set getItemgenerals() {
        return this.itemgenerals;
    }

    public void setItemgenerals(Set itemgenerals) {
        this.itemgenerals = itemgenerals;
    }

}