package HibernateDao;

import java.util.HashSet;
import java.util.Set;

/**
 * Currency generated by MyEclipse Persistence Tools
 */

public class Currency implements java.io.Serializable {

    // Fields

    private String curId;

    private String curDesc;

    private Set currencyratesForCurId = new HashSet(0);

    private Set currencyratesForCurId1 = new HashSet(0);

    // Constructors

    /**
     * default constructor
     */
    public Currency() {
    }

    /**
     * minimal constructor
     */
    public Currency(String curId) {
        this.curId = curId;
    }

    /**
     * full constructor
     */
    public Currency(String curId, String curDesc, Set currencyratesForCurId,
                    Set currencyratesForCurId1) {
        this.curId = curId;
        this.curDesc = curDesc;
        this.currencyratesForCurId = currencyratesForCurId;
        this.currencyratesForCurId1 = currencyratesForCurId1;
    }

    // Property accessors

    public String getCurId() {
        return this.curId;
    }

    public void setCurId(String curId) {
        this.curId = curId;
    }

    public String getCurDesc() {
        return this.curDesc;
    }

    public void setCurDesc(String curDesc) {
        this.curDesc = curDesc;
    }

    public Set getCurrencyratesForCurId() {
        return this.currencyratesForCurId;
    }

    public void setCurrencyratesForCurId(Set currencyratesForCurId) {
        this.currencyratesForCurId = currencyratesForCurId;
    }

    public Set getCurrencyratesForCurId1() {
        return this.currencyratesForCurId1;
    }

    public void setCurrencyratesForCurId1(Set currencyratesForCurId1) {
        this.currencyratesForCurId1 = currencyratesForCurId1;
    }

}