package HibernateDao;

import java.util.Date;

/**
 * Eceipt generated by MyEclipse Persistence Tools
 */

public class Eceipt implements java.io.Serializable {

    // Fields

    private Integer keyId;

    private Itemgeneral itemgeneral;

    private Location location;

    private Warehouse warehouse;

    private Stockreason stockreason;

    private String reType;

    private Double qty;

    private String billNo;

    private Double actualQty;

    private Double adJuAmt;

    private Date transDate;

    // Constructors

    /**
     * default constructor
     */
    public Eceipt() {
    }

    /**
     * minimal constructor
     */
    public Eceipt(Integer keyId, Itemgeneral itemgeneral, Location location,
                  Warehouse warehouse, Stockreason stockreason, String reType,
                  Double qty, String billNo, Double actualQty, Double adJuAmt) {
        this.keyId = keyId;
        this.itemgeneral = itemgeneral;
        this.location = location;
        this.warehouse = warehouse;
        this.stockreason = stockreason;
        this.reType = reType;
        this.qty = qty;
        this.billNo = billNo;
        this.actualQty = actualQty;
        this.adJuAmt = adJuAmt;
    }

    /**
     * full constructor
     */
    public Eceipt(Integer keyId, Itemgeneral itemgeneral, Location location,
                  Warehouse warehouse, Stockreason stockreason, String reType,
                  Double qty, String billNo, Double actualQty, Double adJuAmt,
                  Date transDate) {
        this.keyId = keyId;
        this.itemgeneral = itemgeneral;
        this.location = location;
        this.warehouse = warehouse;
        this.stockreason = stockreason;
        this.reType = reType;
        this.qty = qty;
        this.billNo = billNo;
        this.actualQty = actualQty;
        this.adJuAmt = adJuAmt;
        this.transDate = transDate;
    }

    // Property accessors

    public Integer getKeyId() {
        return this.keyId;
    }

    public void setKeyId(Integer keyId) {
        this.keyId = keyId;
    }

    public Itemgeneral getItemgeneral() {
        return this.itemgeneral;
    }

    public void setItemgeneral(Itemgeneral itemgeneral) {
        this.itemgeneral = itemgeneral;
    }

    public Location getLocation() {
        return this.location;
    }

    public void setLocation(Location location) {
        this.location = location;
    }

    public Warehouse getWarehouse() {
        return this.warehouse;
    }

    public void setWarehouse(Warehouse warehouse) {
        this.warehouse = warehouse;
    }

    public Stockreason getStockreason() {
        return this.stockreason;
    }

    public void setStockreason(Stockreason stockreason) {
        this.stockreason = stockreason;
    }

    public String getReType() {
        return this.reType;
    }

    public void setReType(String reType) {
        this.reType = reType;
    }

    public Double getQty() {
        return this.qty;
    }

    public void setQty(Double qty) {
        this.qty = qty;
    }

    public String getBillNo() {
        return this.billNo;
    }

    public void setBillNo(String billNo) {
        this.billNo = billNo;
    }

    public Double getActualQty() {
        return this.actualQty;
    }

    public void setActualQty(Double actualQty) {
        this.actualQty = actualQty;
    }

    public Double getAdJuAmt() {
        return this.adJuAmt;
    }

    public void setAdJuAmt(Double adJuAmt) {
        this.adJuAmt = adJuAmt;
    }

    public Date getTransDate() {
        return this.transDate;
    }

    public void setTransDate(Date transDate) {
        this.transDate = transDate;
    }

}