package HibernateDao;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by MyEclipse Persistence Tools
 */

public class Employee implements java.io.Serializable {

    // Fields

    private String empId;

    private String empDesc;

    private Date birth;

    private String password;

    private String folk;

    private String marri;

    private String family;

    private String collage;

    private String speci;

    private Long wage;

    private Set itemgeneralsForSaleEmpId = new HashSet(0);

    private Set employeeroles = new HashSet(0);

    private Set iusseBillsForHandleEmp = new HashSet(0);

    private Set eceiptBillsForHandleEmp = new HashSet(0);

    private Set iusseBillsForCreateEmp = new HashSet(0);

    private Set eceiptBillsForCreateEmp = new HashSet(0);

    private Set itemgeneralsForPoEmpId = new HashSet(0);

    private Set inventorytags = new HashSet(0);

    // Constructors

    /**
     * default constructor
     */
    public Employee() {
    }

    /**
     * minimal constructor
     */
    public Employee(String empId, String password, Long wage) {
        this.empId = empId;
        this.password = password;
        this.wage = wage;
    }

    /**
     * full constructor
     */
    public Employee(String empId, String empDesc, Date birth, String password,
                    String folk, String marri, String family, String collage,
                    String speci, Long wage, Set itemgeneralsForSaleEmpId,
                    Set employeeroles, Set iusseBillsForHandleEmp,
                    Set eceiptBillsForHandleEmp, Set iusseBillsForCreateEmp,
                    Set eceiptBillsForCreateEmp, Set itemgeneralsForPoEmpId,
                    Set inventorytags) {
        this.empId = empId;
        this.empDesc = empDesc;
        this.birth = birth;
        this.password = password;
        this.folk = folk;
        this.marri = marri;
        this.family = family;
        this.collage = collage;
        this.speci = speci;
        this.wage = wage;
        this.itemgeneralsForSaleEmpId = itemgeneralsForSaleEmpId;
        this.employeeroles = employeeroles;
        this.iusseBillsForHandleEmp = iusseBillsForHandleEmp;
        this.eceiptBillsForHandleEmp = eceiptBillsForHandleEmp;
        this.iusseBillsForCreateEmp = iusseBillsForCreateEmp;
        this.eceiptBillsForCreateEmp = eceiptBillsForCreateEmp;
        this.itemgeneralsForPoEmpId = itemgeneralsForPoEmpId;
        this.inventorytags = inventorytags;
    }

    // Property accessors

    public String getEmpId() {
        return this.empId;
    }

    public void setEmpId(String empId) {
        this.empId = empId;
    }

    public String getEmpDesc() {
        return this.empDesc;
    }

    public void setEmpDesc(String empDesc) {
        this.empDesc = empDesc;
    }

    public Date getBirth() {
        return this.birth;
    }

    public void setBirth(Date birth) {
        this.birth = birth;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getFolk() {
        return this.folk;
    }

    public void setFolk(String folk) {
        this.folk = folk;
    }

    public String getMarri() {
        return this.marri;
    }

    public void setMarri(String marri) {
        this.marri = marri;
    }

    public String getFamily() {
        return this.family;
    }

    public void setFamily(String family) {
        this.family = family;
    }

    public String getCollage() {
        return this.collage;
    }

    public void setCollage(String collage) {
        this.collage = collage;
    }

    public String getSpeci() {
        return this.speci;
    }

    public void setSpeci(String speci) {
        this.speci = speci;
    }

    public Long getWage() {
        return this.wage;
    }

    public void setWage(Long wage) {
        this.wage = wage;
    }

    public Set getItemgeneralsForSaleEmpId() {
        return this.itemgeneralsForSaleEmpId;
    }

    public void setItemgeneralsForSaleEmpId(Set itemgeneralsForSaleEmpId) {
        this.itemgeneralsForSaleEmpId = itemgeneralsForSaleEmpId;
    }

    public Set getEmployeeroles() {
        return this.employeeroles;
    }

    public void setEmployeeroles(Set employeeroles) {
        this.employeeroles = employeeroles;
    }

    public Set getIusseBillsForHandleEmp() {
        return this.iusseBillsForHandleEmp;
    }

    public void setIusseBillsForHandleEmp(Set iusseBillsForHandleEmp) {
        this.iusseBillsForHandleEmp = iusseBillsForHandleEmp;
    }

    public Set getEceiptBillsForHandleEmp() {
        return this.eceiptBillsForHandleEmp;
    }

    public void setEceiptBillsForHandleEmp(Set eceiptBillsForHandleEmp) {
        this.eceiptBillsForHandleEmp = eceiptBillsForHandleEmp;
    }

    public Set getIusseBillsForCreateEmp() {
        return this.iusseBillsForCreateEmp;
    }

    public void setIusseBillsForCreateEmp(Set iusseBillsForCreateEmp) {
        this.iusseBillsForCreateEmp = iusseBillsForCreateEmp;
    }

    public Set getEceiptBillsForCreateEmp() {
        return this.eceiptBillsForCreateEmp;
    }

    public void setEceiptBillsForCreateEmp(Set eceiptBillsForCreateEmp) {
        this.eceiptBillsForCreateEmp = eceiptBillsForCreateEmp;
    }

    public Set getItemgeneralsForPoEmpId() {
        return this.itemgeneralsForPoEmpId;
    }

    public void setItemgeneralsForPoEmpId(Set itemgeneralsForPoEmpId) {
        this.itemgeneralsForPoEmpId = itemgeneralsForPoEmpId;
    }

    public Set getInventorytags() {
        return this.inventorytags;
    }

    public void setInventorytags(Set inventorytags) {
        this.inventorytags = inventorytags;
    }

}