package HibernateDao;

/**
 * Employeerole generated by MyEclipse Persistence Tools
 */

public class Employeerole implements java.io.Serializable {

    // Fields

    private Integer employeeRoleId;

    private Employee employee;

    private Rolemaster rolemaster;

    // Constructors

    /**
     * default constructor
     */
    public Employeerole() {
    }

    /**
     * full constructor
     */
    public Employeerole(Integer employeeRoleId, Employee employee,
                        Rolemaster rolemaster) {
        this.employeeRoleId = employeeRoleId;
        this.employee = employee;
        this.rolemaster = rolemaster;
    }

    // Property accessors

    public Integer getEmployeeRoleId() {
        return this.employeeRoleId;
    }

    public void setEmployeeRoleId(Integer employeeRoleId) {
        this.employeeRoleId = employeeRoleId;
    }

    public Employee getEmployee() {
        return this.employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    public Rolemaster getRolemaster() {
        return this.rolemaster;
    }

    public void setRolemaster(Rolemaster rolemaster) {
        this.rolemaster = rolemaster;
    }

}