package HibernateDao;

/**
 * Inventorytag generated by MyEclipse Persistence Tools
 */

public class Inventorytag implements java.io.Serializable {

    // Fields

    private Integer lable;

    private Warehouse warehouse;

    private Employee employee;

    private Location location;

    private Itemgeneral itemgeneral;

    private String incZero;

    private String incNega;

    // Constructors

    /**
     * default constructor
     */
    public Inventorytag() {
    }

    /**
     * minimal constructor
     */
    public Inventorytag(Integer lable, Warehouse warehouse, Location location,
                        Itemgeneral itemgeneral, String incZero, String incNega) {
        this.lable = lable;
        this.warehouse = warehouse;
        this.location = location;
        this.itemgeneral = itemgeneral;
        this.incZero = incZero;
        this.incNega = incNega;
    }

    /**
     * full constructor
     */
    public Inventorytag(Integer lable, Warehouse warehouse, Employee employee,
                        Location location, Itemgeneral itemgeneral, String incZero,
                        String incNega) {
        this.lable = lable;
        this.warehouse = warehouse;
        this.employee = employee;
        this.location = location;
        this.itemgeneral = itemgeneral;
        this.incZero = incZero;
        this.incNega = incNega;
    }

    // Property accessors

    public Integer getLable() {
        return this.lable;
    }

    public void setLable(Integer lable) {
        this.lable = lable;
    }

    public Warehouse getWarehouse() {
        return this.warehouse;
    }

    public void setWarehouse(Warehouse warehouse) {
        this.warehouse = warehouse;
    }

    public Employee getEmployee() {
        return this.employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    public Location getLocation() {
        return this.location;
    }

    public void setLocation(Location location) {
        this.location = location;
    }

    public Itemgeneral getItemgeneral() {
        return this.itemgeneral;
    }

    public void setItemgeneral(Itemgeneral itemgeneral) {
        this.itemgeneral = itemgeneral;
    }

    public String getIncZero() {
        return this.incZero;
    }

    public void setIncZero(String incZero) {
        this.incZero = incZero;
    }

    public String getIncNega() {
        return this.incNega;
    }

    public void setIncNega(String incNega) {
        this.incNega = incNega;
    }

}