package HibernateDao;

/**
 * Itemlocation generated by MyEclipse Persistence Tools
 */

public class Itemlocation implements java.io.Serializable {

    // Fields

    private ItemlocationId id;

    private Location location;

    private Warehouse warehouse;

    // Constructors

    /**
     * default constructor
     */
    public Itemlocation() {
    }

    /**
     * full constructor
     */
    public Itemlocation(ItemlocationId id, Location location,
                        Warehouse warehouse) {
        this.id = id;
        this.location = location;
        this.warehouse = warehouse;
    }

    // Property accessors

    public ItemlocationId getId() {
        return this.id;
    }

    public void setId(ItemlocationId id) {
        this.id = id;
    }

    public Location getLocation() {
        return this.location;
    }

    public void setLocation(Location location) {
        this.location = location;
    }

    public Warehouse getWarehouse() {
        return this.warehouse;
    }

    public void setWarehouse(Warehouse warehouse) {
        this.warehouse = warehouse;
    }

}