package HibernateDao;

import java.util.HashSet;
import java.util.Set;

/**
 * Rolemaster generated by MyEclipse Persistence Tools
 */

public class Rolemaster implements java.io.Serializable {

    // Fields

    private String roleId;

    private String roleName;

    private Set roleactions = new HashSet(0);

    private Set employeeroles = new HashSet(0);

    // Constructors

    /**
     * default constructor
     */
    public Rolemaster() {
    }

    /**
     * minimal constructor
     */
    public Rolemaster(String roleId) {
        this.roleId = roleId;
    }

    /**
     * full constructor
     */
    public Rolemaster(String roleId, String roleName, Set roleactions,
                      Set employeeroles) {
        this.roleId = roleId;
        this.roleName = roleName;
        this.roleactions = roleactions;
        this.employeeroles = employeeroles;
    }

    // Property accessors

    public String getRoleId() {
        return this.roleId;
    }

    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    public String getRoleName() {
        return this.roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public Set getRoleactions() {
        return this.roleactions;
    }

    public void setRoleactions(Set roleactions) {
        this.roleactions = roleactions;
    }

    public Set getEmployeeroles() {
        return this.employeeroles;
    }

    public void setEmployeeroles(Set employeeroles) {
        this.employeeroles = employeeroles;
    }

}