package HibernateDao;

/**
 * Roleaction generated by MyEclipse Persistence Tools
 */

public class Roleaction implements java.io.Serializable {

    // Fields

    private Integer roleActionId;

    private Actionmaster actionmaster;

    private Rolemaster rolemaster;

    // Constructors

    /**
     * default constructor
     */
    public Roleaction() {
    }

    /**
     * full constructor
     */
    public Roleaction(Integer roleActionId, Actionmaster actionmaster,
                      Rolemaster rolemaster) {
        this.roleActionId = roleActionId;
        this.actionmaster = actionmaster;
        this.rolemaster = rolemaster;
    }

    // Property accessors

    public Integer getRoleActionId() {
        return this.roleActionId;
    }

    public void setRoleActionId(Integer roleActionId) {
        this.roleActionId = roleActionId;
    }

    public Actionmaster getActionmaster() {
        return this.actionmaster;
    }

    public void setActionmaster(Actionmaster actionmaster) {
        this.actionmaster = actionmaster;
    }

    public Rolemaster getRolemaster() {
        return this.rolemaster;
    }

    public void setRolemaster(Rolemaster rolemaster) {
        this.rolemaster = rolemaster;
    }

}