package HibernateDao;

import java.util.HashSet;
import java.util.Set;

/**
 * Shipvin generated by MyEclipse Persistence Tools
 */

public class Shipvin implements java.io.Serializable {

    // Fields

    private String shipviaId;

    private String shipviaDesc;

    private Set vendermasters = new HashSet(0);

    // Constructors

    /**
     * default constructor
     */
    public Shipvin() {
    }

    /**
     * minimal constructor
     */
    public Shipvin(String shipviaId, String shipviaDesc) {
        this.shipviaId = shipviaId;
        this.shipviaDesc = shipviaDesc;
    }

    /**
     * full constructor
     */
    public Shipvin(String shipviaId, String shipviaDesc, Set vendermasters) {
        this.shipviaId = shipviaId;
        this.shipviaDesc = shipviaDesc;
        this.vendermasters = vendermasters;
    }

    // Property accessors

    public String getShipviaId() {
        return this.shipviaId;
    }

    public void setShipviaId(String shipviaId) {
        this.shipviaId = shipviaId;
    }

    public String getShipviaDesc() {
        return this.shipviaDesc;
    }

    public void setShipviaDesc(String shipviaDesc) {
        this.shipviaDesc = shipviaDesc;
    }

    public Set getVendermasters() {
        return this.vendermasters;
    }

    public void setVendermasters(Set vendermasters) {
        this.vendermasters = vendermasters;
    }

}