package HibernateDao;

/**
 * Shipaddr generated by MyEclipse Persistence Tools
 */

public class Shipaddr implements java.io.Serializable {

    // Fields

    private String shipId;

    private String shipDec;

    private String shipCity;

    private String state;

    // Constructors

    /**
     * default constructor
     */
    public Shipaddr() {
    }

    /**
     * minimal constructor
     */
    public Shipaddr(String shipId) {
        this.shipId = shipId;
    }

    /**
     * full constructor
     */
    public Shipaddr(String shipId, String shipDec, String shipCity, String state) {
        this.shipId = shipId;
        this.shipDec = shipDec;
        this.shipCity = shipCity;
        this.state = state;
    }

    // Property accessors

    public String getShipId() {
        return this.shipId;
    }

    public void setShipId(String shipId) {
        this.shipId = shipId;
    }

    public String getShipDec() {
        return this.shipDec;
    }

    public void setShipDec(String shipDec) {
        this.shipDec = shipDec;
    }

    public String getShipCity() {
        return this.shipCity;
    }

    public void setShipCity(String shipCity) {
        this.shipCity = shipCity;
    }

    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

}