package HibernateDao;

import java.util.HashSet;
import java.util.Set;

/**
 * Stockreason generated by MyEclipse Persistence Tools
 */

public class Stockreason implements java.io.Serializable {

    // Fields

    private String reaCode;

    private String reaDesc;

    private Set eceipts = new HashSet(0);

    private Set iusses = new HashSet(0);

    // Constructors

    /**
     * default constructor
     */
    public Stockreason() {
    }

    /**
     * minimal constructor
     */
    public Stockreason(String reaCode, String reaDesc) {
        this.reaCode = reaCode;
        this.reaDesc = reaDesc;
    }

    /**
     * full constructor
     */
    public Stockreason(String reaCode, String reaDesc, Set eceipts, Set iusses) {
        this.reaCode = reaCode;
        this.reaDesc = reaDesc;
        this.eceipts = eceipts;
        this.iusses = iusses;
    }

    // Property accessors

    public String getReaCode() {
        return this.reaCode;
    }

    public void setReaCode(String reaCode) {
        this.reaCode = reaCode;
    }

    public String getReaDesc() {
        return this.reaDesc;
    }

    public void setReaDesc(String reaDesc) {
        this.reaDesc = reaDesc;
    }

    public Set getEceipts() {
        return this.eceipts;
    }

    public void setEceipts(Set eceipts) {
        this.eceipts = eceipts;
    }

    public Set getIusses() {
        return this.iusses;
    }

    public void setIusses(Set iusses) {
        this.iusses = iusses;
    }

}