package HibernateDao;

import java.util.HashSet;
import java.util.Set;

/**
 * Vendtype generated by MyEclipse Persistence Tools
 */

public class Vendtype implements java.io.Serializable {

    // Fields

    private String vendtypeId;

    private String vendtypeDesc;

    private Set vendermasters = new HashSet(0);

    // Constructors

    /**
     * default constructor
     */
    public Vendtype() {
    }

    /**
     * minimal constructor
     */
    public Vendtype(String vendtypeId) {
        this.vendtypeId = vendtypeId;
    }

    /**
     * full constructor
     */
    public Vendtype(String vendtypeId, String vendtypeDesc, Set vendermasters) {
        this.vendtypeId = vendtypeId;
        this.vendtypeDesc = vendtypeDesc;
        this.vendermasters = vendermasters;
    }

    // Property accessors

    public String getVendtypeId() {
        return this.vendtypeId;
    }

    public void setVendtypeId(String vendtypeId) {
        this.vendtypeId = vendtypeId;
    }

    public String getVendtypeDesc() {
        return this.vendtypeDesc;
    }

    public void setVendtypeDesc(String vendtypeDesc) {
        this.vendtypeDesc = vendtypeDesc;
    }

    public Set getVendermasters() {
        return this.vendermasters;
    }

    public void setVendermasters(Set vendermasters) {
        this.vendermasters = vendermasters;
    }

}