/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sanqing.struts.form;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import javax.servlet.http.HttpServletRequest;

/**
 * MyEclipse Struts
 * Creation date: 04-18-2008
 * <p>
 * XDoclet definition:
 *
 * @struts.form name="actionEditorForm"
 */
public class ActionEditorForm extends ActionForm {
    /*
	 * Generated fields
	 */

    /**
     * action_group property
     */
    private String action_group;

    /**
     * action_id property
     */
    private String action_id;

    /**
     * action_desc property
     */
    private String action_desc;

	/*
	 * Generated Methods
	 */

    /**
     * Method validate
     *
     * @param mapping
     * @param request
     * @return ActionErrors
     */
    public ActionErrors validate(ActionMapping mapping,
                                 HttpServletRequest request) {
        // TODO Auto-generated method stub
        return null;
    }

    /**
     * Method reset
     *
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // TODO Auto-generated method stub
    }

    /**
     * Returns the action_group.
     *
     * @return String
     */
    public String getAction_group() {
        return action_group;
    }

    /**
     * Set the action_group.
     *
     * @param action_group The action_group to set
     */
    public void setAction_group(String action_group) {
        this.action_group = action_group;
    }

    /**
     * Returns the action_id.
     *
     * @return String
     */
    public String getAction_id() {
        return action_id;
    }

    /**
     * Set the action_id.
     *
     * @param action_id The action_id to set
     */
    public void setAction_id(String action_id) {
        this.action_id = action_id;
    }

    /**
     * Returns the action_desc.
     *
     * @return String
     */
    public String getAction_desc() {
        return action_desc;
    }

    /**
     * Set the action_desc.
     *
     * @param action_desc The action_desc to set
     */
    public void setAction_desc(String action_desc) {
        this.action_desc = action_desc;
    }
}