/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sanqing.struts.form;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import javax.servlet.http.HttpServletRequest;

/**
 * MyEclipse Struts
 * Creation date: 04-18-2008
 * <p>
 * XDoclet definition:
 *
 * @struts.form name="currencyEditorForm"
 */
public class CurrencyEditorForm extends ActionForm {
    /*
	 * Generated fields
	 */

    /**
     * cur_id property
     */
    private String cur_id;

    /**
     * cur_desc property
     */
    private String cur_desc;

	/*
	 * Generated Methods
	 */

    /**
     * Method validate
     *
     * @param mapping
     * @param request
     * @return ActionErrors
     */
    public ActionErrors validate(ActionMapping mapping,
                                 HttpServletRequest request) {
        // TODO Auto-generated method stub
        return null;
    }

    /**
     * Method reset
     *
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // TODO Auto-generated method stub
    }

    /**
     * Returns the cur_id.
     *
     * @return String
     */
    public String getCur_id() {
        return cur_id;
    }

    /**
     * Set the cur_id.
     *
     * @param cur_id The cur_id to set
     */
    public void setCur_id(String cur_id) {
        this.cur_id = cur_id;
    }

    /**
     * Returns the cur_desc.
     *
     * @return String
     */
    public String getCur_desc() {
        return cur_desc;
    }

    /**
     * Set the cur_desc.
     *
     * @param cur_desc The cur_desc to set
     */
    public void setCur_desc(String cur_desc) {
        this.cur_desc = cur_desc;
    }
}