/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sanqing.struts.form;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import javax.servlet.http.HttpServletRequest;

/**
 * MyEclipse Struts
 * Creation date: 04-20-2008
 * <p>
 * XDoclet definition:
 *
 * @struts.form name="itemeditorForm"
 */
public class ItemeditorForm extends ActionForm {
    /*
	 * Generated fields
	 */

    /**
     * um_id property
     */
    private String um_id;

    /**
     * color property
     */
    private String color;

    /**
     * whol_pic property
     */
    private String whol_pic;

    /**
     * po_emp_id property
     */
    private String po_emp_id;

    /**
     * item_desc property
     */
    private String item_desc;

    /**
     * prod_code property
     */
    private String prod_code;

    /**
     * status property
     */
    private String status;

    /**
     * tax_rate property
     */
    private String tax_rate;

    /**
     * sale_emp_id property
     */
    private String sale_emp_id;

    /**
     * item_id property
     */
    private String item_id;

    /**
     * sale_pic property
     */
    private String sale_pic;

	/*
	 * Generated Methods
	 */

    /**
     * Method validate
     *
     * @param mapping
     * @param request
     * @return ActionErrors
     */
    public ActionErrors validate(ActionMapping mapping,
                                 HttpServletRequest request) {
        // TODO Auto-generated method stub
        return null;
    }

    /**
     * Method reset
     *
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // TODO Auto-generated method stub
    }

    /**
     * Returns the um_id.
     *
     * @return String
     */
    public String getUm_id() {
        return um_id;
    }

    /**
     * Set the um_id.
     *
     * @param um_id The um_id to set
     */
    public void setUm_id(String um_id) {
        this.um_id = um_id;
    }

    /**
     * Returns the color.
     *
     * @return String
     */
    public String getColor() {
        return color;
    }

    /**
     * Set the color.
     *
     * @param color The color to set
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * Returns the whol_pic.
     *
     * @return String
     */
    public String getWhol_pic() {
        return whol_pic;
    }

    /**
     * Set the whol_pic.
     *
     * @param whol_pic The whol_pic to set
     */
    public void setWhol_pic(String whol_pic) {
        this.whol_pic = whol_pic;
    }

    /**
     * Returns the po_emp_id.
     *
     * @return String
     */
    public String getPo_emp_id() {
        return po_emp_id;
    }

    /**
     * Set the po_emp_id.
     *
     * @param po_emp_id The po_emp_id to set
     */
    public void setPo_emp_id(String po_emp_id) {
        this.po_emp_id = po_emp_id;
    }

    /**
     * Returns the item_desc.
     *
     * @return String
     */
    public String getItem_desc() {
        return item_desc;
    }

    /**
     * Set the item_desc.
     *
     * @param item_desc The item_desc to set
     */
    public void setItem_desc(String item_desc) {
        this.item_desc = item_desc;
    }

    /**
     * Returns the prod_code.
     *
     * @return String
     */
    public String getProd_code() {
        return prod_code;
    }

    /**
     * Set the prod_code.
     *
     * @param prod_code The prod_code to set
     */
    public void setProd_code(String prod_code) {
        this.prod_code = prod_code;
    }

    /**
     * Returns the status.
     *
     * @return String
     */
    public String getStatus() {
        return status;
    }

    /**
     * Set the status.
     *
     * @param status The status to set
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Returns the tax_rate.
     *
     * @return String
     */
    public String getTax_rate() {
        return tax_rate;
    }

    /**
     * Set the tax_rate.
     *
     * @param tax_rate The tax_rate to set
     */
    public void setTax_rate(String tax_rate) {
        this.tax_rate = tax_rate;
    }

    /**
     * Returns the sale_emp_id.
     *
     * @return String
     */
    public String getSale_emp_id() {
        return sale_emp_id;
    }

    /**
     * Set the sale_emp_id.
     *
     * @param sale_emp_id The sale_emp_id to set
     */
    public void setSale_emp_id(String sale_emp_id) {
        this.sale_emp_id = sale_emp_id;
    }

    /**
     * Returns the item_id.
     *
     * @return String
     */
    public String getItem_id() {
        return item_id;
    }

    /**
     * Set the item_id.
     *
     * @param item_id The item_id to set
     */
    public void setItem_id(String item_id) {
        this.item_id = item_id;
    }

    /**
     * Returns the sale_pic.
     *
     * @return String
     */
    public String getSale_pic() {
        return sale_pic;
    }

    /**
     * Set the sale_pic.
     *
     * @param sale_pic The sale_pic to set
     */
    public void setSale_pic(String sale_pic) {
        this.sale_pic = sale_pic;
    }
}