/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sanqing.struts.form;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import javax.servlet.http.HttpServletRequest;

/**
 * MyEclipse Struts
 * Creation date: 04-20-2008
 * <p>
 * XDoclet definition:
 *
 * @struts.form name="locationeditorForm"
 */
public class LocationeditorForm extends ActionForm {
    /*
	 * Generated fields
	 */

    /**
     * loca_id property
     */
    private String loca_id;

    /**
     * loca_desc property
     */
    private String loca_desc;

	/*
	 * Generated Methods
	 */

    /**
     * Method validate
     *
     * @param mapping
     * @param request
     * @return ActionErrors
     */
    public ActionErrors validate(ActionMapping mapping,
                                 HttpServletRequest request) {
        // TODO Auto-generated method stub
        return null;
    }

    /**
     * Method reset
     *
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // TODO Auto-generated method stub
    }

    /**
     * Returns the loca_id.
     *
     * @return String
     */
    public String getLoca_id() {
        return loca_id;
    }

    /**
     * Set the loca_id.
     *
     * @param loca_id The loca_id to set
     */
    public void setLoca_id(String loca_id) {
        this.loca_id = loca_id;
    }

    /**
     * Returns the loca_desc.
     *
     * @return String
     */
    public String getLoca_desc() {
        return loca_desc;
    }

    /**
     * Set the loca_desc.
     *
     * @param loca_desc The loca_desc to set
     */
    public void setLoca_desc(String loca_desc) {
        this.loca_desc = loca_desc;
    }
}