/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sanqing.struts.form;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import javax.servlet.http.HttpServletRequest;

/**
 * MyEclipse Struts
 * Creation date: 04-18-2008
 * <p>
 * XDoclet definition:
 *
 * @struts.form name="roleEditorForm"
 */
public class RoleEditorForm extends ActionForm {
    /*
	 * Generated fields
	 */

    /**
     * role_name property
     */
    private String role_name;

    /**
     * role_id property
     */
    private String role_id;

	/*
	 * Generated Methods
	 */

    /**
     * Method validate
     *
     * @param mapping
     * @param request
     * @return ActionErrors
     */
    public ActionErrors validate(ActionMapping mapping,
                                 HttpServletRequest request) {
        // TODO Auto-generated method stub
        return null;
    }

    /**
     * Method reset
     *
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // TODO Auto-generated method stub
    }

    /**
     * Returns the role_name.
     *
     * @return String
     */
    public String getRole_name() {
        return role_name;
    }

    /**
     * Set the role_name.
     *
     * @param role_name The role_name to set
     */
    public void setRole_name(String role_name) {
        this.role_name = role_name;
    }

    /**
     * Returns the role_id.
     *
     * @return String
     */
    public String getRole_id() {
        return role_id;
    }

    /**
     * Set the role_id.
     *
     * @param role_id The role_id to set
     */
    public void setRole_id(String role_id) {
        this.role_id = role_id;
    }
}