/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sanqing.struts.form;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import javax.servlet.http.HttpServletRequest;

/**
 * MyEclipse Struts
 * Creation date: 04-18-2008
 * <p>
 * XDoclet definition:
 *
 * @struts.form name="shipvinEditorForm"
 */
public class ShipvinEditorForm extends ActionForm {
    /*
	 * Generated fields
	 */

    /**
     * shipvia_desc property
     */
    private String shipvia_desc;

    /**
     * shipvia_id property
     */
    private String shipvia_id;

	/*
	 * Generated Methods
	 */

    /**
     * Method validate
     *
     * @param mapping
     * @param request
     * @return ActionErrors
     */
    public ActionErrors validate(ActionMapping mapping,
                                 HttpServletRequest request) {
        // TODO Auto-generated method stub
        return null;
    }

    /**
     * Method reset
     *
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // TODO Auto-generated method stub
    }

    /**
     * Returns the shipvia_desc.
     *
     * @return String
     */
    public String getShipvia_desc() {
        return shipvia_desc;
    }

    /**
     * Set the shipvia_desc.
     *
     * @param shipvia_desc The shipvia_desc to set
     */
    public void setShipvia_desc(String shipvia_desc) {
        this.shipvia_desc = shipvia_desc;
    }

    /**
     * Returns the shipvia_id.
     *
     * @return String
     */
    public String getShipvia_id() {
        return shipvia_id;
    }

    /**
     * Set the shipvia_id.
     *
     * @param shipvia_id The shipvia_id to set
     */
    public void setShipvia_id(String shipvia_id) {
        this.shipvia_id = shipvia_id;
    }
}