/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sanqing.struts.form;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import javax.servlet.http.HttpServletRequest;

/**
 * MyEclipse Struts
 * Creation date: 04-18-2008
 * <p>
 * XDoclet definition:
 *
 * @struts.form name="ummasterForm"
 */
public class UmmasterForm extends ActionForm {
    /*
	 * Generated fields
	 */

    /**
     * um_id property
     */
    private String um_id;

    /**
     * um_desc property
     */
    private String um_desc;

	/*
	 * Generated Methods
	 */

    /**
     * Method validate
     *
     * @param mapping
     * @param request
     * @return ActionErrors
     */
    public ActionErrors validate(ActionMapping mapping,
                                 HttpServletRequest request) {
        // TODO Auto-generated method stub
        return null;
    }

    /**
     * Method reset
     *
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // TODO Auto-generated method stub
    }

    /**
     * Returns the um_id.
     *
     * @return String
     */
    public String getUm_id() {
        return um_id;
    }

    /**
     * Set the um_id.
     *
     * @param um_id The um_id to set
     */
    public void setUm_id(String um_id) {
        this.um_id = um_id;
    }

    /**
     * Returns the um_desc.
     *
     * @return String
     */
    public String getUm_desc() {
        return um_desc;
    }

    /**
     * Set the um_desc.
     *
     * @param um_desc The um_desc to set
     */
    public void setUm_desc(String um_desc) {
        this.um_desc = um_desc;
    }
}