/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sanqing.struts.form;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import javax.servlet.http.HttpServletRequest;

/**
 * MyEclipse Struts
 * Creation date: 04-18-2008
 * <p>
 * XDoclet definition:
 *
 * @struts.form name="userEditorForm"
 */
public class UserEditorForm extends ActionForm {
    /*
	 * Generated fields
	 */

    /**
     * validpassword property
     */
    private String validpassword;

    /**
     * password property
     */
    private String password;

    /**
     * emp_desc property
     */
    private String emp_desc;

    /**
     * family property
     */
    private String family;

    /**
     * collage property
     */
    private String collage;

    /**
     * speci property
     */
    private String speci;

    /**
     * folk property
     */
    private String folk;

    /**
     * birth property
     */
    private String birth;

    /**
     * emp_id property
     */
    private String emp_id;

    /**
     * wage property
     */
    private String wage;

    /**
     * marri property
     */
    private String marri;

	/*
	 * Generated Methods
	 */

    /**
     * Method validate
     *
     * @param mapping
     * @param request
     * @return ActionErrors
     */
    public ActionErrors validate(ActionMapping mapping,
                                 HttpServletRequest request) {
        // TODO Auto-generated method stub
        return null;
    }

    /**
     * Method reset
     *
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // TODO Auto-generated method stub
    }

    /**
     * Returns the validpassword.
     *
     * @return String
     */
    public String getValidpassword() {
        return validpassword;
    }

    /**
     * Set the validpassword.
     *
     * @param validpassword The validpassword to set
     */
    public void setValidpassword(String validpassword) {
        this.validpassword = validpassword;
    }

    /**
     * Returns the password.
     *
     * @return String
     */
    public String getPassword() {
        return password;
    }

    /**
     * Set the password.
     *
     * @param password The password to set
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Returns the emp_desc.
     *
     * @return String
     */
    public String getEmp_desc() {
        return emp_desc;
    }

    /**
     * Set the emp_desc.
     *
     * @param emp_desc The emp_desc to set
     */
    public void setEmp_desc(String emp_desc) {
        this.emp_desc = emp_desc;
    }

    /**
     * Returns the family.
     *
     * @return String
     */
    public String getFamily() {
        return family;
    }

    /**
     * Set the family.
     *
     * @param family The family to set
     */
    public void setFamily(String family) {
        this.family = family;
    }

    /**
     * Returns the collage.
     *
     * @return String
     */
    public String getCollage() {
        return collage;
    }

    /**
     * Set the collage.
     *
     * @param collage The collage to set
     */
    public void setCollage(String collage) {
        this.collage = collage;
    }

    /**
     * Returns the speci.
     *
     * @return String
     */
    public String getSpeci() {
        return speci;
    }

    /**
     * Set the speci.
     *
     * @param speci The speci to set
     */
    public void setSpeci(String speci) {
        this.speci = speci;
    }

    /**
     * Returns the folk.
     *
     * @return String
     */
    public String getFolk() {
        return folk;
    }

    /**
     * Set the folk.
     *
     * @param folk The folk to set
     */
    public void setFolk(String folk) {
        this.folk = folk;
    }

    /**
     * Returns the birth.
     *
     * @return String
     */
    public String getBirth() {
        return birth;
    }

    /**
     * Set the birth.
     *
     * @param birth The birth to set
     */
    public void setBirth(String birth) {
        this.birth = birth;
    }

    /**
     * Returns the emp_id.
     *
     * @return String
     */
    public String getEmp_id() {
        return emp_id;
    }

    /**
     * Set the emp_id.
     *
     * @param emp_id The emp_id to set
     */
    public void setEmp_id(String emp_id) {
        this.emp_id = emp_id;
    }

    /**
     * Returns the wage.
     *
     * @return String
     */
    public String getWage() {
        return wage;
    }

    /**
     * Set the wage.
     *
     * @param wage The wage to set
     */
    public void setWage(String wage) {
        this.wage = wage;
    }

    /**
     * Returns the marri.
     *
     * @return String
     */
    public String getMarri() {
        return marri;
    }

    /**
     * Set the marri.
     *
     * @param marri The marri to set
     */
    public void setMarri(String marri) {
        this.marri = marri;
    }
}