/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sanqing.struts.form;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import javax.servlet.http.HttpServletRequest;

/**
 * MyEclipse Struts
 * Creation date: 04-18-2008
 * <p>
 * XDoclet definition:
 *
 * @struts.form name="userRoleEditorForm"
 */
public class UserRoleEditorForm extends ActionForm {
    /*
	 * Generated fields
	 */

    /**
     * allroles property
     */
    private String allroles;

    /**
     * userroles property
     */
    private String userroles;

	/*
	 * Generated Methods
	 */

    /**
     * Method validate
     *
     * @param mapping
     * @param request
     * @return ActionErrors
     */
    public ActionErrors validate(ActionMapping mapping,
                                 HttpServletRequest request) {
        // TODO Auto-generated method stub
        return null;
    }

    /**
     * Method reset
     *
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // TODO Auto-generated method stub
    }

    /**
     * Returns the allroles.
     *
     * @return String
     */
    public String getAllroles() {
        return allroles;
    }

    /**
     * Set the allroles.
     *
     * @param allroles The allroles to set
     */
    public void setAllroles(String allroles) {
        this.allroles = allroles;
    }

    /**
     * Returns the userroles.
     *
     * @return String
     */
    public String getUserroles() {
        return userroles;
    }

    /**
     * Set the userroles.
     *
     * @param userroles The userroles to set
     */
    public void setUserroles(String userroles) {
        this.userroles = userroles;
    }
}