/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sanqing.struts.form;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import javax.servlet.http.HttpServletRequest;

/**
 * MyEclipse Struts
 * Creation date: 04-19-2008
 * <p>
 * XDoclet definition:
 *
 * @struts.form name="venderEditorForm"
 */
public class VenderEditorForm extends ActionForm {
    /*
	 * Generated fields
	 */

    /**
     * vend_type property
     */
    private String vend_type;

    /**
     * vend_nati property
     */
    private String vend_nati;

    /**
     * vend_nati property
     */
    private String vend_city;

    /**
     * vend_addr property
     */
    private String vend_addr;

    /**
     * vend_email property
     */
    private String vend_email;

    /**
     * vend_phone property
     */
    private String vend_phone;

    /**
     * vend_desc property
     */
    private String vend_desc;

    /**
     * tradeamount property
     */
    private String tradeamount;

    /**
     * vend_shipvia property
     */
    private String vend_shipvia;

    /**
     * vend_id property
     */
    private String vend_id;

    /**
     * vend_post property
     */
    private String vend_post;

    /**
     * cont_man property
     */
    private String cont_man;
	
	/*
	 * Generated Methods
	 */

    /**
     * Method validate
     *
     * @param mapping
     * @param request
     * @return ActionErrors
     */
    public ActionErrors validate(ActionMapping mapping,
                                 HttpServletRequest request) {
        // TODO Auto-generated method stub
        return null;
    }

    /**
     * Method reset
     *
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // TODO Auto-generated method stub
    }

    /**
     * Returns the vend_type.
     *
     * @return String
     */
    public String getVend_type() {
        return vend_type;
    }

    /**
     * Set the vend_type.
     *
     * @param vend_type The vend_type to set
     */
    public void setVend_type(String vend_type) {
        this.vend_type = vend_type;
    }

    /**
     * Returns the vend_nati.
     *
     * @return String
     */
    public String getVend_nati() {
        return vend_nati;
    }


    /**
     * Set the vend_nati.
     *
     * @param vend_nati The vend_nati to set
     */
    public void setVend_nati(String vend_nati) {
        this.vend_nati = vend_nati;
    }

    /**
     * Returns the vend_nati.
     *
     * @return String
     */
    public String getVend_city() {
        return this.vend_city;
    }


    /**
     * Set the vend_nati.
     *
     * @param vend_nati The vend_nati to set
     */
    public void setVend_city(String vend_city) {
        this.vend_city = vend_city;
    }

    /**
     * Returns the vend_addr.
     *
     * @return String
     */
    public String getVend_addr() {
        return vend_addr;
    }

    /**
     * Set the vend_addr.
     *
     * @param vend_addr The vend_addr to set
     */
    public void setVend_addr(String vend_addr) {
        this.vend_addr = vend_addr;
    }

    /**
     * Returns the vend_email.
     *
     * @return String
     */
    public String getVend_email() {
        return vend_email;
    }

    /**
     * Set the vend_email.
     *
     * @param vend_email The vend_email to set
     */
    public void setVend_email(String vend_email) {
        this.vend_email = vend_email;
    }

    /**
     * Returns the vend_phone.
     *
     * @return String
     */
    public String getVend_phone() {
        return vend_phone;
    }

    /**
     * Set the vend_phone.
     *
     * @param vend_phone The vend_phone to set
     */
    public void setVend_phone(String vend_phone) {
        this.vend_phone = vend_phone;
    }

    /**
     * Returns the vend_desc.
     *
     * @return String
     */
    public String getVend_desc() {
        return vend_desc;
    }

    /**
     * Set the vend_desc.
     *
     * @param vend_desc The vend_desc to set
     */
    public void setVend_desc(String vend_desc) {
        this.vend_desc = vend_desc;
    }

    /**
     * Returns the tradeamount.
     *
     * @return String
     */
    public String getTradeamount() {
        return tradeamount;
    }

    /**
     * Set the tradeamount.
     *
     * @param tradeamount The tradeamount to set
     */
    public void setTradeamount(String tradeamount) {
        this.tradeamount = tradeamount;
    }

    /**
     * Returns the vend_shipvia.
     *
     * @return String
     */
    public String getVend_shipvia() {
        return vend_shipvia;
    }

    /**
     * Set the vend_shipvia.
     *
     * @param vend_shipvia The vend_shipvia to set
     */
    public void setVend_shipvia(String vend_shipvia) {
        this.vend_shipvia = vend_shipvia;
    }

    /**
     * Returns the vend_id.
     *
     * @return String
     */
    public String getVend_id() {
        return vend_id;
    }

    /**
     * Set the vend_id.
     *
     * @param vend_id The vend_id to set
     */
    public void setVend_id(String vend_id) {
        this.vend_id = vend_id;
    }

    /**
     * Returns the vend_post.
     *
     * @return String
     */
    public String getVend_post() {
        return vend_post;
    }

    /**
     * Set the vend_post.
     *
     * @param vend_post The vend_post to set
     */
    public void setVend_post(String vend_post) {
        this.vend_post = vend_post;
    }

    /**
     * Returns the cont_man.
     *
     * @return String
     */
    public String getCont_man() {
        return cont_man;
    }

    /**
     * Set the cont_man.
     *
     * @param cont_man The cont_man to set
     */
    public void setCont_man(String cont_man) {
        this.cont_man = cont_man;
    }
}