/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sanqing.struts.form;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import javax.servlet.http.HttpServletRequest;

/**
 * MyEclipse Struts
 * Creation date: 04-20-2008
 * <p>
 * XDoclet definition:
 *
 * @struts.form name="venderTypeEditorForm"
 */
public class VenderTypeEditorForm extends ActionForm {
    /*
	 * Generated fields
	 */

    /**
     * vendtype_desc property
     */
    private String vendtype_desc;

    /**
     * vendtype_id property
     */
    private String vendtype_id;

	/*
	 * Generated Methods
	 */

    /**
     * Method validate
     *
     * @param mapping
     * @param request
     * @return ActionErrors
     */
    public ActionErrors validate(ActionMapping mapping,
                                 HttpServletRequest request) {
        // TODO Auto-generated method stub
        return null;
    }

    /**
     * Method reset
     *
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // TODO Auto-generated method stub
    }

    /**
     * Returns the vendtype_desc.
     *
     * @return String
     */
    public String getVendtype_desc() {
        return vendtype_desc;
    }

    /**
     * Set the vendtype_desc.
     *
     * @param vendtype_desc The vendtype_desc to set
     */
    public void setVendtype_desc(String vendtype_desc) {
        this.vendtype_desc = vendtype_desc;
    }

    /**
     * Returns the vendtype_id.
     *
     * @return String
     */
    public String getVendtype_id() {
        return vendtype_id;
    }

    /**
     * Set the vendtype_id.
     *
     * @param vendtype_id The vendtype_id to set
     */
    public void setVendtype_id(String vendtype_id) {
        this.vendtype_id = vendtype_id;
    }
}